### ISSUE TITLE
(Feature) Internationalization

### ISSUE THREAD

**Issue by joevingracien** [SimeonGriggs/sanity-remix-preview#15]
Hello,
First of all thank you very much for this example and guide, it has been incredibly helpful.

I wondered if you thought it would be relevant to add internationalization in this example ? 
I think it's a really common use case most of us will face / implement and this could be really valuable to have an official example with best practices to rely on.

Best regards,
Joevin

**Comment by SimeonGriggs** [comment]
Yeah i18n is super common, but it would bloat this deliberately-clean template. Thanks for the suggestion though!
