### ISSUE TITLE
Cloudflare Pages

### ISSUE THREAD

**Issue by joevingracien** [SimeonGriggs/sanity-remix-preview#16]
I have been trying to get this working with Cloudflare Pages but I can't figure out a way to do so. (process not available in Cloudflare Pages.)

Could you tell what files and code needs to be changed or may have some guidance please ?

**Comment by SimeonGriggs** [comment]
You'd need to [look for guidance](https://www.jacobparis.com/content/cloudflare-remix) on switching over Node things like process to Cloudflare's equivalents

**Comment by joevingracien** [comment]
Thank you for the provided link, I'll dig deeper.
